<a href="https://colab.research.google.com/github/priyankamb2725/Priyankamb09/blob/main/NLPexp4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data_out= pd.read_csv('/content/twitter4000.csv')

In [ ]:
data_out= pd.read_csv('/content/twitter4000.csv')
pattern = r'\w+@\w+\.\w+' #pattern for mailID
data_out['twitts'].apply(lambda x: re.sub(pattern,'',x)) #twitts is input

data_out['twitts'].apply(lambda x : re.findall(pattern, x ))

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\w+'



data_out['twitts'].apply(lambda x : re.findall(pattern, x ))

0       [is, bored, and, wants, to, watch, a, movie, a...
1           [back, in, miami, waiting, to, unboard, ship]
2       [misskpey, awwww, dnt, dis, brng, bak, memorie...
3                 [ughhh, i, am, so, tired, blahhhhhhhhh]
4       [mandagoforth, me, bad, It, s, funny, though, ...
                              ...
3995                                 [i, just, graduated]
3996      [Templating, works, it, all, has, to, be, done]
3997                [mommy, just, brought, me, starbucks]
3998    [omarepps, watching, you, on, a, House, re, ru...
3999    [Thanks, for, trying, to, make, me, smile, I, ...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\b[A-Za-z.+-]@[A-Za-z.].[A-Z|a-z]{2,}\b' #pattern for emails

In [ ]:
data_out['twitts'].apply(lambda x : re.findall(pattern, x ))

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
#https:gmail.com
pattern = r'http\s+ | wwww\s+'
data = data_out['twitts'].apply(lambda x : re.findall(pattern, x ))
data.value_counts()

twitts
[]    4000
Name: count, dtype: int64

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Bluetooth is used in phones and for connecting devices.")

filtered_words = [token.text for token in doc if not token.is_stop]
print(filtered_words)

['Bluetooth', 'phones', 'connecting', 'devices', '.']

In [1]:
import re
import spacy


nlp = spacy.load("en_core_web_sm")

def clean_text_spacy(text):

    text = re.sub(r'<.*?>', '', text)


    text = re.sub(r'http\S+|www\S+|https\S+', '', text)


    text = re.sub(r'\S+@\S+', '', text)


    text = re.sub(r'\d+', '', text)


    doc = nlp(text)

    cleaned_tokens = []

    for token in doc:

        if not token.is_stop and not token.is_punct and not token.is_space:

            cleaned_tokens.append(token.lemma_.lower())

    return " ".join(cleaned_tokens)



raw_text = """
<p>Hello! Contact us at support@gmail.com</p>
Visit our website: https://example.com
We are running and runs faster. Numbers: 12345
"""


cleaned_text = clean_text_spacy(raw_text)

print("Original Text:\n", raw_text)
print("\nCleaned Text:\n", cleaned_text)

Original Text:

<p>Hello! Contact us at support@gmail.com</p>
Visit our website: https://example.com
We are running and runs faster. Numbers: 12345


Cleaned Text:
 hello contact visit website run run fast number